# Generated by Django 4.1.4 on 2023-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_project_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fullDesc',
            new_name='full_Desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='shortDesc',
            new_name='short_Desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
