# Generated by Django 4.1.4 on 2023-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_proj_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_image',
            name='image',
            field=models.ImageField(upload_to='Project_Image'),
        ),
    ]
