# Generated by Django 4.1.4 on 2023-02-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_proj_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='default_image',
        ),
    ]
