# Generated by Django 4.1.4 on 2023-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_project_discounted_price_alter_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
