# Generated by Django 4.1.4 on 2023-02-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_project_discounted_price_alter_project_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
