# Generated by Django 4.1.4 on 2023-02-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
