# Generated by Django 4.1.4 on 2023-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_project_id_cart_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=15, null=True)),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', (('Front-end Development', 'Front-end Development'), ('JavaScript', 'JavaScript'), ('AJAX', 'AJAX'), ('Node Js', 'Node Js'), ('React Js', 'React Js'), ('Angular Js', 'Angular Js'), ('Django', 'Django'), ('PHP', 'PHP'), ('C#', 'C#'))), ('Android Development', (('Java', 'Java'), ('kotlin', 'Kotlin'))), ('Cyber Security', 'Cyber Security'), ('Others', (('C', 'C'), ('C++', 'C++'), ('Python', 'Python')))], max_length=100),
        ),
    ]
