# Generated by Django 4.1.4 on 2023-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='phone',
            field=models.IntegerField(blank=True, default='0', max_length=15, null=True),
        ),
    ]
