# Generated by Django 4.1.4 on 2023-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_detail_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_image',
            name='image',
            field=models.ImageField(upload_to='Project_Image/'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='phone',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profileImg',
            field=models.ImageField(blank=True, default='/defaultImg/person-circle.png', null=True, upload_to='Profile_Image/'),
        ),
    ]
