# Generated by Django 4.1.4 on 2023-02-21 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 8, 20, 47, 662480, tzinfo=datetime.timezone.utc)),
        ),
    ]
