# Generated by Django 4.1.4 on 2023-02-22 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_order_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj_image',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='proj_image',
            old_name='proj_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 23, 11, 55, 978737)),
        ),
    ]
