# Generated by Django 4.1.4 on 2023-02-22 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_rename_image_proj_image_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj_image',
            old_name='project',
            new_name='proj_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 23, 21, 51, 898261)),
        ),
    ]
